// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiBbZbM0Ls0PKEJ6yu2OTFc2XDssKhik',
    appId: '1:463274298540:web:41ce320190e1a1f5112309',
    messagingSenderId: '463274298540',
    projectId: 'pushnotification-8e3f1',
    authDomain: 'pushnotification-8e3f1.firebaseapp.com',
    storageBucket: 'pushnotification-8e3f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMFGdYM2e7LcH7HN2kMTuO7ZG35OS0_M',
    appId: '1:463274298540:android:36757d95aa7a6306112309',
    messagingSenderId: '463274298540',
    projectId: 'pushnotification-8e3f1',
    storageBucket: 'pushnotification-8e3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySFou69-RbClvnkHzJMTFaOt07Ti-dY0',
    appId: '1:463274298540:ios:e540a36b095dcbc8112309',
    messagingSenderId: '463274298540',
    projectId: 'pushnotification-8e3f1',
    storageBucket: 'pushnotification-8e3f1.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySFou69-RbClvnkHzJMTFaOt07Ti-dY0',
    appId: '1:463274298540:ios:e540a36b095dcbc8112309',
    messagingSenderId: '463274298540',
    projectId: 'pushnotification-8e3f1',
    storageBucket: 'pushnotification-8e3f1.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
